
import { useState, useEffect, useRef } from 'react';
import { cn } from '@/lib/utils';

const faqItems = [
  {
    question: 'What does ScaleX AI do?',
    answer: 'ScaleX AI is a cutting-edge platform that enables website personalization at scale for paid media. It allows advertisers to generate unlimited landing page variations tailored to different channels, audiences, and campaigns.'
  },
  {
    question: 'How does ScaleX AI improve ad performance?',
    answer: 'By dynamically personalizing website experiences for each visitor, ScaleX AI increases engagement, boosts conversion rates, and enhances Quality Scores on platforms like Google Ads—ultimately reducing Customer Acquisition Cost (CAC).'
  },
  {
    question: 'How fast can I generate personalized website experiences?',
    answer: 'After a one-time set of 15 minutes, you can create high-converting website variations in minutes instead of weeks.'
  },
  {
    question: 'Do I need to make changes to my website backend or advertising tags?',
    answer: 'No, ScaleX AI seamlessly integrates with your existing tech infrastructure. All it requires is inserting a small JavaScript code, which takes just 15 minutes to implement—no backend changes or tag modifications needed.'
  },
  {
    question: 'Which website platforms does ScaleX AI support?',
    answer: 'ScaleX AI is compatible with all website platforms, including WordPress, Shopify, Wix, Webflow, and custom-built platforms. '
  },
  {
    question: 'Can I test multiple experiences at once?',
    answer: 'Yes! ScaleX AI enables continuous A/B and multivariate testing at a granular keyword, ad, or audience level to optimize performance in real time.'
  },
  {
    question: 'Which advertising channels does ScaleX AI support?',
    answer: 'ScaleX AI works across all major paid media channels, including Google Ads, Facebook, Instagram, LinkedIn, and more.'
  },
  {
    question: 'How much performance lift can I expect?',
    answer: 'Advertisers typically see a 10-30% improvement in conversion rates. Some have even achieved up to 3X higher conversions with ScaleX AI’s personalized experiences.'
  },
  {
    question: 'How much does ScaleX AI cost?',
    answer: 'Pricing is customized based on your needs. Please contact us for a tailored quote.'
  },
   {
    question: 'Where are the personalized experiences generated by ScaleX AI hosted?',
    answer: 'All personalized pages created by ScaleX AI are hosted on the advertiser’s own servers, ensuring full control, security, and compliance with existing infrastructure.'
   } 

];

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);
  const observerRef = useRef<IntersectionObserver | null>(null);
  
  useEffect(() => {
    observerRef.current = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add('revealed');
          observerRef.current?.unobserve(entry.target);
        }
      });
    }, { threshold: 0.1 });
    
    const elements = document.querySelectorAll('.reveal-on-scroll');
    elements.forEach((el) => observerRef.current?.observe(el));
    
    return () => {
      if (observerRef.current) {
        elements.forEach((el) => observerRef.current?.unobserve(el));
      }
    };
  }, []);

  const toggleQuestion = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section id="FAQs" className="py-20 relative overflow-hidden">
      <div className="section-container">
        <div className="text-center mb-16 reveal-on-scroll">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">FAQs</h2>
          <p className="max-w-2xl mx-auto text-white/70">
            Find answers to commonly asked questions about ScaleX AI and how it can transform your research workflow.
          </p>
        </div>
        
        <div className="max-w-3xl mx-auto">
          {faqItems.map((item, index) => (
            <div 
              key={index}
              className={cn(
                "border-b border-white/10 last:border-0 reveal-on-scroll",
                index > 0 && `animate-delay-${(index % 5) * 100}`
              )}
            >
              <button 
                className="flex justify-between items-center w-full py-5 text-left focus:outline-none"
                onClick={() => toggleQuestion(index)}
              >
                <h3 className="text-lg font-medium">{item.question}</h3>
                <span className="text-scalex-lightBlue">
                  {openIndex === index ? (
                    <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M6 12H18" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                    </svg>
                  ) : (
                    <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M12 6V18M6 12H18" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
                    </svg>
                  )}
                </span>
              </button>
              <div
                className={cn(
                  "overflow-hidden transition-all duration-300 ease-in-out",
                  openIndex === index ? "max-h-96 pb-5" : "max-h-0"
                )}
              >
                <p className="text-white/70">{item.answer}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FAQ;
